import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const dist = path.join(root, 'dist');
const portable = path.join(root, 'release', 'WoW-Guide-Manager-0.1.0-portable');
const makePortable = process.argv.includes('--portable');

function stripExports(source) {
  return source.replaceAll('export const ', 'const ').replaceAll('export function ', 'function ');
}

function stripImports(source) {
  return source
    .split('\n')
    .filter((line) => !line.trimStart().startsWith('import '))
    .join('\n');
}

async function createBundle(target) {
  const guides = stripExports(await readFile(path.join(root, 'src/data/guides.js'), 'utf8'));
  const classGuides = stripExports(await readFile(path.join(root, 'src/data/classGuides.js'), 'utf8'));
  const classBuildGuides = stripExports(await readFile(path.join(root, 'src/data/classBuildGuides.js'), 'utf8'));
  const specGuides = stripExports(await readFile(path.join(root, 'src/data/specGuides.js'), 'utf8'));
  const dungeons = stripExports(await readFile(path.join(root, 'src/data/dungeonGuides.js'), 'utf8'));
  const professions = stripExports(await readFile(path.join(root, 'src/data/professionGuides.js'), 'utf8'));
  const assets = stripExports(await readFile(path.join(root, 'src/data/assetManifest.js'), 'utf8'));
  const subscriptions = stripExports(await readFile(path.join(root, 'src/data/subscriptions.js'), 'utf8'));
  const filters = stripExports(await readFile(path.join(root, 'src/lib/filterGuides.js'), 'utf8'));
  const app = stripImports(await readFile(path.join(root, 'src/app.js'), 'utf8'));
  const bundle = ['// Generated by scripts/build.mjs for file:// portable usage.', guides, classGuides, classBuildGuides, specGuides, dungeons, professions, assets, subscriptions, filters, app].join('\n\n');

  await writeFile(path.join(target, 'src/app.bundle.js'), bundle, 'utf8');
}

async function createWindowsData(target) {
  const [guidesModule, classModule, buildModule, specModule, dungeonModule, professionModule, subscriptionModule, assetModule] = await Promise.all([
    import('../src/data/guides.js'),
    import('../src/data/classGuides.js'),
    import('../src/data/classBuildGuides.js'),
    import('../src/data/specGuides.js'),
    import('../src/data/dungeonGuides.js'),
    import('../src/data/professionGuides.js'),
    import('../src/data/subscriptions.js'),
    import('../src/data/assetManifest.js')
  ]);

  const data = {
    generatedAt: new Date().toISOString(),
    expansions: guidesModule.expansions,
    categories: guidesModule.categories,
    guideCards: guidesModule.guideCards,
    classGuides: classModule.classGuides,
    classBuildGuides: buildModule.classBuildGuides,
    specGuides: specModule.specGuides,
    dungeonGuides: dungeonModule.dungeonGuides,
    professionGuides: professionModule.professionGuides,
    subscriptionTiers: subscriptionModule.subscriptionTiers,
    assetManifest: assetModule.assetManifest
  };

  await mkdir(target, { recursive: true });
  await writeFile(path.join(target, 'app-data.json'), JSON.stringify(data, null, 2), 'utf8');
}

async function copyApp(target, { bundleForFileProtocol } = { bundleForFileProtocol: false }) {
  await mkdir(target, { recursive: true });
  await cp(path.join(root, 'index.html'), path.join(target, 'index.html'));
  await cp(path.join(root, 'src'), path.join(target, 'src'), { recursive: true });
  await cp(path.join(root, 'assets'), path.join(target, 'assets'), { recursive: true });

  if (bundleForFileProtocol) {
    const indexPath = path.join(target, 'index.html');
    const index = await readFile(indexPath, 'utf8');
    await writeFile(
      indexPath,
      index.replace('<script type="module" src="./src/app.js"></script>', '<script defer src="./src/app.bundle.js"></script>'),
      'utf8'
    );
    await createBundle(target);
  }
}

async function main() {
  await rm(dist, { recursive: true, force: true });
  await copyApp(dist, { bundleForFileProtocol: true });

  if (makePortable) {
    await rm(portable, { recursive: true, force: true });
    await copyApp(path.join(portable, 'app'), { bundleForFileProtocol: true });
    await cp(path.join(root, 'windows'), path.join(portable, 'windows'), { recursive: true });
    await createWindowsData(path.join(portable, 'windows'));
    await writeFile(
      path.join(portable, 'WoW Guide Manager.cmd'),
      '@echo off\r\nsetlocal\r\ncall "%~dp0windows\\Start-WoWGuideManager.cmd"\r\n',
      'utf8'
    );
    await writeFile(
      path.join(portable, 'README-PORTABLE.txt'),
      'WoW Guide Manager portable MVP\r\n\r\nStart: Doppelklicke "WoW Guide Manager.cmd". Die Windows-App startet ueber PowerShell/WPF. Der Browser-Build liegt zusaetzlich in app\\index.html.\r\nAlle Dateien bleiben im portablen Ordner.\r\n',
      'utf8'
    );
  }

  if (!existsSync(path.join(dist, 'index.html'))) {
    throw new Error('Build failed: dist/index.html was not created.');
  }

  if (!existsSync(path.join(dist, 'src/app.bundle.js'))) {
    throw new Error('Build failed: dist/src/app.bundle.js was not created.');
  }

  console.log(makePortable ? `Portable build created: ${portable}` : `Build created: ${dist}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
